### ISSUE TITLE
Stuck on liking picture

### ISSUE THREAD

**Issue by wegmanjunior** [sudoguy/tiktokpy#62]
Hi there, Thank you so much for sharing the library, i have a problem though, the bottom half of the example code works fine, but when i try to call the like function, it gets stuck at "Going to @ video page for like. how do i solve this, Thanks!

**Comment by wegmanjunior** [comment]
Same goes for following by the way, it can't seem to load the page.

**Comment by sudoguy** [comment]
@wegmanjunior Thanks for the issue. I will check this issue in the next few days.  Perhaps the html has been changed and needs to be fixed

**Comment by wegmanjunior** [comment]
Thanks for the quick response! I'll see if i can find the problem, but i'm fairly new to python so fingers crossed!

**Comment by wegmanjunior** [comment]
I think the problem is in the following line in /tiktokpy/user.py:
`await page.click(".video-feed-container .lazyload-wrapper:first-child .bar-item-img") `
because none of the three css classes are present in the html of the website, i would experiment with trying different css classes but i have no idea how to change an imported library. Or maybe i'm saying complete nonsense, but i hope this discovery helped a bit! Thanks again for publishing this.

**Comment by sudoguy** [comment]
@wegmanjunior you're right! I just fixed the css selector for like() and unlike() then tried to run example and it worked. Now a new version is released - 0.8.6. Try upgrading with `pip install -U tiktokpy`

**Comment by wegmanjunior** [comment]
@sudoguy for me it's still not working, updated and restarted the program

**Comment by wegmanjunior** [comment]
@sudoguy i can't seem to get it to work... Also the "following" action doesn't seem to work for me, which works in a different way... are there any additional libraries i have to have installed?

**Comment by tobeyond** [comment]
How did you get so far?
Mine won't go any further than "Getting trending items"
